---
title: "2019tba_growth"
author: "Greg Marra"
date: "4/27/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(lubridate)
require("ggrepel")

source("get_tba_data.R")

mondays <- c(
  ymd(20190304), 
  ymd(20190311),
  ymd(20190318),
  ymd(20190325),
  ymd(20190401),
  ymd(20190408),
  ymd(20190415),
  ymd(20190422),
  ymd(20190429)
)

remap_week <- function(event_code2, current_week) {
  week_remaps = tribble(
    ~event_code, ~week,
    "arc", 8,
    "cars", 8,
    "carv", 7,
    "cmpmi", 8,
    "cmptx", 7,
    "cur", 8,
    "dal", 8,
    "dar", 8,
    "gal", 7,
    "hop", 7,
    "new", 7,
    "roe", 7,
    "tes", 8,
    "tur", 7
  )
    
  lookup_week <- week_remaps %>% filter(event_code==event_code2) %>% .$week
  if (length(lookup_week) > 0) {
    return(lookup_week)
  } else {
    return(current_week)
  }
}

events <- getEvents("2019") %>% 
  filter(
    !event_type_string %in% c("Preseason", "Offseason")
  ) %>%
  rowwise %>%
  mutate(
    week = remap_week(event_code, week)
  ) %>%
  as.data.frame()

# check champs weeks are filled in
no_week <- events %>%
  filter(is.na(week)) %>%
  select(event_code)

teams <- events$event_code %>% 
  map(~ getEventTeamsKeys("2019", .x))

events <- events %>%
  add_column(teams)

event_teams <- events %>%
  unnest(teams) %>%
  select(year, event_code, teams, week)

week_team_counts <- event_teams %>%
  group_by(week) %>%
  count()

# Data from https://console.firebase.google.com/project/tbatv-prod-hrd/analytics/app/android:com.thebluealliance.androidclient/overview%3Ft=1&params=_u.date00%253D20190222%2526_u.date01%253D20190426&cs=app.m.dashboard.overview&g=1
waps = tribble(
  ~ds, ~week, ~wap,
  mondays[1], 0, 16885,
  mondays[2], 1, 27144,
  mondays[3], 2, 29246,
  mondays[4], 3, 29584,
  mondays[5], 4, 32353,
  mondays[6], 5, 29146,
  mondays[7], 6, 23551,
  mondays[8], 7, 25770,
  mondays[9], 8, 25082
)

waps <- waps %>% 
  left_join(week_team_counts, by = "week") %>%
  mutate(
    wap_per_team = wap/ n,
    week = week + 1 # fix week offset for pretty display
  )
```

## 2019 The Blue Alliance Usage Analysis

How does the number of teams competing affect weekly usage?

```{r wap_vs_teams}
waps %>%
  ggplot(aes(x = n, y = wap, label = week)) +
  geom_point() +
  geom_text_repel() +
  labs(
    title = "Teams Competing Drives Usage",
    subtitle = "Labeled with Week Number",
    x = "Week's Teams Competing",
    y = "Weekly Active People"
  )
```



```{r wap_per_team}
waps %>%
  ggplot(aes(x = week, y = wap_per_team)) +
  geom_col() +
  labs(
    title = "Teams Competiting Drives Usage",
    subtitle = "Later weeks have higher WAP / Team due to (District) Champs?",
    x = "Week",
    y = "Weekly Active People / Teams Competing"
  ) +
  scale_x_continuous(breaks=c(0,1,2,3,4,5,6,7,8,9))
``` 

